// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCj7Lje7826R1r04VZzB9Rlp090DpT9W4o',
    appId: '1:358193397735:web:84f3b914ad442b8e538742',
    messagingSenderId: '358193397735',
    projectId: 'ecom-2e378',
    authDomain: 'ecom-2e378.firebaseapp.com',
    databaseURL: 'ecom-2e378-default-rtdb.firebaseio.com',
    storageBucket: 'ecom-2e378.appspot.com',
    measurementId: 'G-YWPF22Q9PK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9dsby9Jp73mr8GVuUYHp7NigB1NCccdc',
    appId: '1:358193397735:android:bc36dc01fea9e293538742',
    messagingSenderId: '358193397735',
    databaseURL: 'ecom-2e378-default-rtdb.firebaseio.com',
    authDomain: 'ecom-2e378.firebaseapp.com',
    projectId: 'ecom-2e378',
    storageBucket: 'ecom-2e378.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxT3C1Q4kNZKuxXx4_pLNbEIoPVAlv1L8',
    appId: '1:358193397735:ios:de4cad0b7ce1c487538742',
    messagingSenderId: '358193397735',
    projectId: 'ecom-2e378',
    storageBucket: 'ecom-2e378.appspot.com',
    iosBundleId: 'com.example.ecom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxT3C1Q4kNZKuxXx4_pLNbEIoPVAlv1L8',
    appId: '1:358193397735:ios:de4cad0b7ce1c487538742',
    messagingSenderId: '358193397735',
    projectId: 'ecom-2e378',
    storageBucket: 'ecom-2e378.appspot.com',
    iosBundleId: 'com.example.ecom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCj7Lje7826R1r04VZzB9Rlp090DpT9W4o',
    appId: '1:358193397735:web:87f0eb7d5b828a51538742',
    messagingSenderId: '358193397735',
    projectId: 'ecom-2e378',
    authDomain: 'ecom-2e378.firebaseapp.com',
    storageBucket: 'ecom-2e378.appspot.com',
    measurementId: 'G-ZDSDL8F7D6',
  );
}
